package com.zhou.mypowerbee.model.dto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import com.zhou.mypowerbee.model.entity.User;

/**
 * Entity mapped to table USER_DTO.
 */
public class UserInfoDTO extends BaseDTO {
    public UserDTO Data;

    @Override
    public String errMsg() {
        if (!isSuccess()) {
            if (Code == 1003) {
                return "访问太快,请稍后一分钟再试";
            }
        }
        return null;
    }

    public static class UserDTO {

        public User toUser() {
            User user = new User();
            user.setUuid(getUuid());
            user.setAid(getAid());
            user.setUserid(getUserid());
            user.setNick(getNick());
            user.setPass(getPass());
            user.setTel(getTel());
            user.setPhone(getPhone());
            user.setAddr(getAddr());
            user.setEmail(getEmail());
            user.setBirthday(getBirthday());
            user.setSign(getSign());
            user.setCompany(getCompany());
            user.setOffice(getOffice());
            user.setImtoken(getImtoken());
            user.setOpenid(getOpenid());
            user.setAvatarpath(getAvatarpath());
            user.setIsman(isIsman());
            user.setAdmin(getAdmin());
            return user;
        }

        /**  */
        private String Uuid;

        public String getUuid() {
            return this.Uuid;
        }

        public void setUuid(String Uuid) {
            this.Uuid = Uuid;
        }

        /**  */
        private String Aid;

        public String getAid() {
            return this.Aid;
        }

        public void setAid(String Aid) {
            this.Aid = Aid;
        }

        /**  */
        private String Userid;

        public String getUserid() {
            return this.Userid;
        }

        public void setUserid(String Userid) {
            this.Userid = Userid;
        }

        /**  */
        private String Nick;

        public String getNick() {
            return this.Nick;
        }

        public void setNick(String Nick) {
            this.Nick = Nick;
        }

        /**  */
        private String Pass;

        public String getPass() {
            return this.Pass;
        }

        public void setPass(String Pass) {
            this.Pass = Pass;
        }

        /**  */
        private String Tel;

        public String getTel() {
            return this.Tel;
        }

        public void setTel(String Tel) {
            this.Tel = Tel;
        }

        /**  */
        private String Phone;

        public String getPhone() {
            return this.Phone;
        }

        public void setPhone(String Phone) {
            this.Phone = Phone;
        }

        /**  */
        private String Addr;

        public String getAddr() {
            return this.Addr;
        }

        public void setAddr(String Addr) {
            this.Addr = Addr;
        }

        /**  */
        private String Email;

        public String getEmail() {
            return this.Email;
        }

        public void setEmail(String Email) {
            this.Email = Email;
        }

        /**  */
        private String Birthday;

        public String getBirthday() {
            return this.Birthday;
        }

        public void setBirthday(String Birthday) {
            this.Birthday = Birthday;
        }

        /**  */
        private String Sign;

        public String getSign() {
            return this.Sign;
        }

        public void setSign(String Sign) {
            this.Sign = Sign;
        }

        /**  */
        private String Company;

        public String getCompany() {
            return this.Company;
        }

        public void setCompany(String Company) {
            this.Company = Company;
        }

        /**  */
        private String Office;

        public String getOffice() {
            return this.Office;
        }

        public void setOffice(String Office) {
            this.Office = Office;
        }

        /**  */
        private String Imtoken;

        public String getImtoken() {
            return this.Imtoken;
        }

        public void setImtoken(String Imtoken) {
            this.Imtoken = Imtoken;
        }

        /**  */
        private String Openid;

        public String getOpenid() {
            return this.Openid;
        }

        public void setOpenid(String Openid) {
            this.Openid = Openid;
        }

        /**  */
        private String Avatarpath;

        public String getAvatarpath() {
            return this.Avatarpath;
        }

        public void setAvatarpath(String Avatarpath) {
            this.Avatarpath = Avatarpath;
        }

        /**  */
        private boolean Isman;

        public boolean isIsman() {
            return this.Isman;
        }

        public void setIsman(boolean Isman) {
            this.Isman = Isman;
        }

        /**  */
        private int Admin;

        public int getAdmin() {
            return this.Admin;
        }

        public void setAdmin(int Admin) {
            this.Admin = Admin;
        }

        /**  */
        private int Status;

        public int getStatus() {
            return this.Status;
        }

        public void setStatus(int Status) {
            this.Status = Status;
        }

        /**  */
        private Expand Expand;

        public Expand getExpand() {
            return this.Expand;
        }

        public void setExpand(Expand Expand) {
            this.Expand = Expand;
        }

        /**  */
        private String Adduid;

        public String getAdduid() {
            return this.Adduid;
        }

        public void setAdduid(String Adduid) {
            this.Adduid = Adduid;
        }

        /**  */
        private String Lastuid;

        public String getLastuid() {
            return this.Lastuid;
        }

        public void setLastuid(String Lastuid) {
            this.Lastuid = Lastuid;
        }

        /**  */
        private String Addtime;

        public String getAddtime() {
            return this.Addtime;
        }

        public void setAddtime(String Addtime) {
            this.Addtime = Addtime;
        }

        /**  */
        private String Lasttime;

        public String getLasttime() {
            return this.Lasttime;
        }

        public void setLasttime(String Lasttime) {
            this.Lasttime = Lasttime;
        }

        class Expand {
            /**  */
            private String accessToken;

            public String getAccessToken() {
                return this.accessToken;
            }

            public void setAccessToken(String accessToken) {
                this.accessToken = accessToken;
            }

            /**  */
            private String date;

            public String getDate() {
                return this.date;
            }

            public void setDate(String date) {
                this.date = date;
            }

            /**  */
            private String userId;

            public String getUserId() {
                return this.userId;
            }

            public void setUserId(String userId) {
                this.userId = userId;
            }
        }
    }
}
